kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: {{ name }}
  namespace: eessibasis
  labels:
    team: eessibasis
spec:
  image: {{ image }}
  ingresses:
    - {{ ingress }}
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        diskAutoresize: true
        tier: {{ database.tier }}
        databases:
          - name: {{ database.name }}
            envVarPrefix:
              DATABASE
  liveness:
    path: /actuator/health
    port: 8080
    initialDelay: 20
    timeout: 70
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /actuator/health
    port: 8080
    initialDelay: 20
    timeout: 70
  replicas:
    min: {{ replicas.min }}
    max: {{ replicas.max }}
    cpuThresholdPercentage: 60
  resources:
    limits:
      cpu: "1"
      memory: {{ resources.limits.memory }}
    requests:
      cpu: 800m
      memory: {{ resources.requests.memory }}
  azure:
    application:
      enabled: true
      allowAllUsers: true
      replyURLs:
        - "{{ ingress }}/callback"
      claims:
        extra:
          - "NAVident"
    sidecar:
      enabled: true
      autoLogin: true
      autoLoginIgnorePaths:
        - /api/**
  accessPolicy:
    inbound:
      rules:
        - application: {{ application.eux-neessi.name }}
          namespace: {{ application.eux-neessi.namespace }}
          cluster: {{ cluster.fss }}
        - application: {{ application.eux-neessi.name }}
          namespace: {{ application.eux-neessi.namespace }}
          cluster: {{ cluster.gcp }}
        - application: {{ application.eux-fagmodul-journalfoering.name }}
          namespace: {{ application.eux-fagmodul-journalfoering.namespace }}
          cluster: {{ cluster.fss }}
        - application: {{ application.eux-fagmodul-journalfoering.name }}
          namespace: {{ application.eux-fagmodul-journalfoering.namespace }}
          cluster: {{ cluster.gcp }}
        - application: {{ application.eux-journal.name }}
          namespace: {{ application.eux-journal.namespace }}
          cluster: {{ cluster.gcp }}
        - application: {{ application.eux-journalarkivar.name }}
          namespace: {{ application.eux-journalarkivar.namespace }}
          cluster: {{ cluster.gcp }}
        - application: {{ application.eux-barnetrygd.name }}
          namespace: {{ application.eux-barnetrygd.namespace }}
          cluster: {{ cluster.fss }}
        - application: {{ application.eux-barnetrygd.name }}
          namespace: {{ application.eux-barnetrygd.namespace }}
          cluster: {{ cluster.gcp }}
    outbound:
      external:
        - host: oppgave.prod-fss-pub.nais.io
        - host: oppgave.dev-fss-pub.nais.io
        - host: oppgave-q1.dev-fss-pub.nais.io
  env:
    - name: CLIENT_OPPGAVE_ENDPOINT
      value: {{ client.oppgave.endpoint }}
    - name: CLIENT_OPPGAVE_SCOPE
      value: {{ client.oppgave.scope }}
