name: eux-oppgave
ingress: https://eux-oppgave.intern.nav.no

database:
  name: eux-oppgave-db
  tier: db-custom-1-3840

application:
  eux-fagmodul-journalfoering:
    name: eux-fagmodul-journalfoering
    namespace: eessibasis
  eux-journal:
    name: eux-journal
    namespace: eessibasis
  eux-journalarkivar:
    name: eux-journalarkivar
    namespace: eessibasis
  eux-barnetrygd:
    name: eux-barnetrygd
    namespace: eessibasis

client:
  oppgave:
    endpoint: https://oppgave.prod-fss-pub.nais.io
    scope: api://prod-fss.oppgavehandtering.oppgave/.default

cluster:
  fss: prod-fss
  gcp: prod-gcp

resources:
  limits:
    memory: 512Mi
  requests:
    memory: 512Mi

replicas:
  min: 2
  max: 4
