name: eux-oppgave
ingress: https://eux-oppgave.intern.nav.no
database:
  name: eux-oppgave-db
  tier: db-custom-1-3840
application:
  eux-neessi:
    name: eux-neessi
    namespace: eessibasis
  eux-fagmodul-journalfoering:
    name: eux-fagmodul-journalfoering
    namespace: eessibasis
cluster:
  fss: prod-fss
  gcp: prod-gcp
