openapi: 3.0.3
info:
  title: Eux Oppgave API
  description: API til bruk av EUX apper for 책 h책ndtere NAV Oppgaver
  contact:
    name: vegard.lundeberg.hillestad@nav.no
  version: v1
servers:
  - url: 'http://localhost:8080/api/v1'
tags:
  - name: Eux Oppgave API
    description: >-
      API til bruk av EUX apper for 책 h책ndtere NAV Oppgaver

paths:
  '/oppgaver':
    $ref: 'oppgaver/operations_rot.yaml'
  '/oppgaver/behandleSedFraJournalpostId':
    $ref: 'oppgaver/operations_behandleSedFraJournalpostId.yaml'
  '/oppgaver/ferdigstill':
    $ref: 'oppgaver/operations_ferdigstill.yaml'
  '/oppgaver/tildelEnhetsnr':
    $ref: 'oppgaver/operations_tildelEnhetsnr.yaml'
  '/oppgaver/finn':
    $ref: 'oppgaver/operations_finn.yaml'
  '/oppgaver/oppgavetype':
    $ref: 'oppgaver/operations_oppgavetype.yaml'
