openapi: 3.0.3
info:
  title: EUX Oppgave API
  description: API til bruk av EUX apper for 책 h책ndtere i NAV Oppgaver
  contact:
    name: vegard.lundeberg.hillestad@nav.no
  version: v1
servers:
  - url: 'http://localhost:8080/api/v1'
tags:
  - name: Nav Rinasak API
    description: >-
      API til bruk av EUX apper for 책 h책ndtere i NAV Oppgaver

paths:
  '/oppgaver':
    $ref: 'oppgaver/operations_rot.yaml'
