openapi: 3.0.3
info:
  title: Eux Oppgave API
  description: API til bruk av EUX apper for å håndtere NAV Oppgaver
  contact:
    name: vegard.lundeberg.hillestad@nav.no
  version: v1
servers:
  - url: '/'
tags:
  - name: Oppgaver
    description: >-
      API til bruk av EUX apper for å håndtere NAV Oppgaver

paths:
  '/api/v1/oppgaver':
    $ref: 'oppgaver/operations_rot.yaml'
  '/api/v1/oppgaver/behandleSedFraJournalpostId':
    $ref: 'oppgaver/operations_behandleSedFraJournalpostId.yaml'
  '/api/v1/oppgaver/ferdigstill':
    $ref: 'oppgaver/operations_ferdigstill.yaml'
  '/api/v1/oppgaver/tildelEnhetsnr':
    $ref: 'oppgaver/operations_tildelEnhetsnr.yaml'
  '/api/v1/oppgaver/finn':
    $ref: 'oppgaver/operations_finn.yaml'
  '/api/v1/oppgaver/oppgavetype':
    $ref: 'oppgaver/operations_oppgavetype.yaml'
